# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  #pre: 
  #  runs-on: ubuntu-latest
  #  steps:
  #  - uses: actions/checkout@v2
  #  - name: Run a multi-line script
  #    run: |
  #      echo Hello Action!
  #  - name: git status
  #    env:
  #      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
  #    run: |
        
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm test
      - name: npm version patch
        run: | 
          git config --global credential.helper 'cache --timeout=3600'
          git config --global user.email "marctimperley@yahoo.co.uk"
          git config --global user.name "MarcTimperley"
          git remote set-url --push origin https://MarcTimperley:$GITHUB_TOKEN@github.com/MarcTimperley/response-dashboard
          npm version patch
          git push origin master
      - run: npm publish
        #run: git commit -m "version patch"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}

  #publish-npm:
   # needs: patch
    #runs-on: ubuntu-latest
    #steps:
     # - uses: actions/checkout@v2
     # - uses: actions/setup-node@v1
     #   with:
     #     node-version: 12
     #     registry-url: https://registry.npmjs.org/
     # - run: npm ci
     # - run: npm publish
     #   env:
     #     NODE_AUTH_TOKEN: ${{secrets.npm_token}}
